# Generated by Django 3.2.5 on 2021-08-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsstory_ing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='ing',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='img_url',
            field=models.URLField(default='https://place-puppy.com/300x300'),
        ),
    ]
